name: main
on:
  push:
    branches: [master]
  schedule:
  閿燂拷 cron: '0 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    閿燂拷 uses: actions/checkout@v1
    閿燂拷 uses: actions/setup-python@v1
    閿燂拷 run: pip install pre-commit-mirror-maker
    閿燂拷 run: git config --global user.name pre-commit
    閿燂拷 run: git config --global user.email pre-commit@example.com
    閿燂拷 run: pre-commit-mirror . --language=python --package-name=django --types=python
    閿燂拷 run: pre-commit-mirror . --language=python --package-name=flake8 --types=python
    閿燂拷 run: pre-commit-mirror . --language=python --package-name=autopep8 --types=python --args=-i
    閿燂拷 run: pre-commit-mirror . --language=python --package-name=isort --types=python
    閿燂拷 run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/master --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
